galaxy_info:
  role_name: docker_init
  description: Настройка серверов для работы с Docker
  author: Ignashov Roman
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
