galaxy_info:
  role_name: swarm_init
  description: Инициализация кластера swarm
  author: Ignashov Roman
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
